### PR TITLE
docs: note public mode disables advanced settings

### PR DESCRIPTION
**Pull request by jtagcat**
Closes #1911 / #1912

### CODE REVIEW

**Comment by jtagcat** [comment]
Making docs proprietary in the future doesn't sound good, @CLAassistant is wrong, I have revoked the agreement, through https://cla-assistant.io/

**Comment by graciousgrey** [comment]
Plonk.

**Comment by lastzero** [comment]
Dear @jtagcat: You seem to speak from experience. What is your most successful Open Source project?

We don't want companies like Amazon stealing our work before we've even reached our [first funding goal](https://github.com/sponsors/photoprism).

That's a big problem in the industry, just like people who open tons of bug reports without first trying to [determine the cause of their problems](https://docs.photoprism.app/getting-started/troubleshooting/).

**Comment by alexislefebvre** [comment]
> We don't want companies like Amazon stealing our work before we've even reached our [first funding goal](https://github.com/sponsors/photoprism).

Isn't it already impossible because of the [Attribution-NonCommercial-ShareAlike 4.0 International license](https://github.com/photoprism/photoprism-docs/blob/master/LICENSE)?

When Elasticsearch changed its license, [Amazon forked it](https://venturebeat.com/2021/07/13/amazons-elasticsearch-fork-opensearch-hits-prime-time/). How changing the license in the future could prevent this?

**Comment by lastzero** [comment]
We otherwise can't change the license anymore, we also can't make it more open if needed.

More importantly, the non-commercial clause generally also applies to maintainers if they do not receive additional rights. We have sponsors and would therefore have to take docs.photoprism.app down. Probably nobody wants that.

The CLA states that we have the freedom to license the documentation (most of which we wrote ourselves) in the way WE want and think it makes sense. The same applies to the source code of the application.

Alternatively, we can no longer accept pull requests if it means losing our freedom. We have spent the last 4 years developing / writing this application and invested all our personal savings. Would that be fair?

Shall we add this to our FAQs?

**Comment by lastzero** [comment]
To be even more explicit, now that we've cleared up the legal questions (while I should actually work on something more important):

1. The comment on our CLA was just another example of @jtagcat trolling around to get attention; the pull request is tiny and really not worth the fuss
2. While we generally appreciate feedback and bug reports, his/her communication was not respectful and mostly wasted our time, hurting the project and its users
3. [We can not accept that](https://github.com/photoprism/photoprism/blob/develop/CODE_OF_CONDUCT.md)

**Pull request closed without merging**
