### PR TITLE
Create hardware-acceleration.md

### PR DESCRIPTION
**Pull request by inthreedee**
Ref: https://github.com/photoprism/photoprism-docs/issues/61

This is just a basic doc to get us started. Once we have more concrete information on recommended GPU/CMA memory allocations for the RPi, we can include those as well. 

@uxusoft

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks! It's a start :) Shall I merge it or are we waiting for @uxusoft's feedback?

**Comment by inthreedee** [comment]
No harm in waiting a bit.

**Review by uxusoft — APPROVED** [review]
Thank you

**Comment by inthreedee** [comment]
Just a note: I didn’t add this to the main navigation yet. I wasn’t sure if there’s enough info here or if we want to wait until we get more answers about memory management.

**Comment by lastzero** [comment]
Already fixed... added more details as well... there is an edit link (upper right corner) so that everyone can easily submit improvements :)

**Comment by lastzero** [comment]
See https://docs.photoprism.org/getting-started/advanced/transcoding/

**Pull request merged**
