### PR TITLE
Show original images

### PR DESCRIPTION
**Pull request by alexislefebvre**
Explain how to use the different settings to view original images when it's possible to not view the thumbnails.

See https://github.com/photoprism/photoprism/issues/627#issuecomment-770302999

### CODE REVIEW

**Comment by graciousgrey** [comment]
Thank you :)

**Comment by Stokel** [comment]
I still can't get Photoprism to show me the original image when clicking on a thumbnail.

The original image is 4032x3024.
Photoprism seems to return 2048x1536
Therefore the image looses detail and the colors are also slightly distorted.

This is in my options.yml
```
JpegQuality: 100
ThumbSize: 2048
ThumbSizeUncached: 2048
ThumbUncached: true
```
photoprism.yaml includes
```
      PHOTOPRISM_THUMB_UNCACHED: "true"             # Shows originals (hopefully?)
      PHOTOPRISM_THUMB_SIZE: 2048
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 2048
```

**Comment by lastzero** [comment]
We didn't perform any changes here. Did you read our docs?
- https://docs.photoprism.org/user-guide/settings/advanced/#dynamic-and-static-size-limits

**Comment by lastzero** [comment]
Also note your screen / browser window must be LARGER than the LARGEST thumb size for the viewer to use a LARGER image.

**Comment by lastzero** [comment]
For colors see:
- https://github.com/photoprism/photoprism/issues/1474

If you want this, please sign up if you're not a sponsor yet. Nothing speeds up development like supporting the developers!

**Comment by lastzero** [comment]
Also a JPEG quality of 100 will result in super large thumbnails consuming lots of storage. We recommend a maximum of 92 or 93.

**Comment by Stokel** [comment]
> Also note your screen / browser window must be LARGER than the LARGEST thumb size for the viewer to use a LARGER image.
Thank you for your fast responses. :)

I read the documentation and followed [this](https://github.com/photoprism/photoprism/issues/627#issuecomment-770302999) comment to "enable" originals.

My screen has a resolution of 3440x1440 and I now also reduced the ThumbSizeUncached and ThumbSize to 1024.
I still get the downscaled version in photoprism. Do I have to clear my cache?
Even if this would work, would this not impact the result of the facial recognition as stated in the documentation?
I'd like to have a way to view my images in their original quality but also have the best possible facial recognition results.

**Comment by lastzero** [comment]
Browsers typically don't produce a good quality when downscaling. It's mentioned in our docs. Sponsors get personal support via email. I can say so much that your specific issue probably is Apple's P3 color space encoding which we need to add support for. The standard libraries we use sadly don't support it, or maybe that was Apple's intention. See link above.

**Comment by lastzero** [comment]
See:
- https://github.com/photoprism/photoprism/discussions/1765#discussioncomment-1711962

**Comment by Stokel** [comment]
Thank you for your detailed responses.
I now also tested to directly open my originals in firefox and chrome and the images returned are indeed worse than the originals opened via e.g. gwenview. (They look about the same as what is returned by Photoprism)
I absolutely love your current work and the progress this project has made (e.g. image recognition) as I'd love to ditch apple and google.

I will have to evaluate if the drop in image quality by using a browser application is a trade-off I am willing to make.

**Comment by alexislefebvre** [comment]
I tested with the last release (20211203) and I still see full image when I look at one. If I do a right click and open the image in a new tab, I see the original image. The built-in zoom of Photoprism doesn't zoom to 100% though (and that's ok).

Here are the settings I use:

```env
      PHOTOPRISM_THUMB_UNCACHED: "true"
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 720
      PHOTOPRISM_THUMB_SIZE: 720
      PHOTOPRISM_THUMB_LIMIT: 3840
      PHOTOPRISM_JPEG_QUALITY: 85
```

**Comment by lastzero** [comment]
This change converts colors to standard sRGB if an Apple "Display P3" color profile is detected:

- https://github.com/photoprism/photoprism/commit/5be456a09f7a846d233649c8de21dbb7f4e1a45a

Not sure if color profile conversion also works when originals are HEIF images, needs to be tested.
Videos and file formats other than JPEG haven't been touched yet.

I'll start a new Development Preview build for testing:
- https://docs.photoprism.org/release-notes/#development-preview

**Pull request merged**
