### PR TITLE
Using HAPROXY as Reverse Proxy

### PR DESCRIPTION
**Pull request by mamema**
This explains, how to configure HAPROXY (WebSocket) connections between your client and backend services.

Example:

# frontend connection handling
# 'photo' is the name of the subdomain
acl			photo	hdr(host) -i photo.example.com
use_backend be_photo_ipvANY  if  photo aclcrt_fe_http

# backend config
# be_photo is the name of the backend
backend be_photo_ipvANY
		mode		http
		id			112
		log			global
		timeout connect		30000
		timeout server		30000
		retries			3
		load-server-state-from-file	global
		timeout queue 5s
		timeout tunnel 2m
		option redispatch
	
		 mode http
		 option forwardfor
		 no option httpclose
	
		 http-request set-header Host photo.example.com
		 http-request del-header  X-Frame-Options
		 http-request del-header  Connection
		 http-request add-header  X-Frame-Options SAMEORIGIN
		 http-request add-header  Connection Upgrade
		
                 # Websocket configuration
                 acl is_websocket hdr(Upgrade) -i WebSocket
		acl is_websocket hdr_beg(Host) -i ws
                 # photoprism ip address and port
		server			photo x.x.x.x:2342 id 106

### CODE REVIEW

**Comment by lastzero** [comment]
Thank you! If you rebase your PR to the head revision and sign the CLA, we can merge this :)

**Comment by mamema** [comment]
i've signed it already... hmm...it's mentioned above

**Comment by lastzero** [comment]
By "rebased" I mean that the pull request is from a version of our documentation that allows us to see the actual changes/additions you made. Right now the pull request has 5,000+ file changes. There can be other reasons for this, but an old repository that a pull request is created from is the most common.

If you can wait a few days, I can help you if needed.

**Comment by mamema** [comment]
yes plz, as it is for the community and i have this already running, it's not needed to get into a hurry

**Comment by alexislefebvre** [comment]
This PR is trying to merge the `userguide` to `master`. This `userguide` branch is outdated: https://github.com/photoprism/photoprism-docs/branches

If you want to make some changes to the doc, go to https://docs.photoprism.app/, then look at the page that you want to modify, then click on the pencil / “Edit this page” icon and follow the instructions.

Another way to make some changes is to [create a fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo), then create a new branch and make some changes, and fonally open a PR to ask to merge this branch.

**Comment by graciousgrey** [comment]
@mamema what .md file exactly did you add or edit ? I can copy your changes to the docs directly independent from this pull request

**Comment by graciousgrey** [comment]
@mamema No worries, I will close this PR. Feel free to just send the text per mail and I can add it to the docs :)

**Pull request closed without merging**
