### PR TITLE
docker-compose: add example with full path

### PR DESCRIPTION
**Pull request by alexislefebvre**
Add one example so that people see different ways to mount directories.

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Related to https://github.com/photoprism/photoprism/issues/642

**Comment by lastzero** [comment]
Thanks! Might need to shorten this a bit for readability later...

**Comment by kurtph1969** [comment]
I would really like to know how to add an external drive to the library. Is this possible?

**Comment by lastzero** [comment]
We'll add examples for Windows to our docs soon. What Windows version and Linux subsystem are you using specifically?

**Comment by kurtph1969** [comment]
Thank you.

I am using Windows 10 and Docker Desktop 3.0.0 (50684). 

[https://docs.docker.com/docker-for-windows/release-notes/](https://docs.docker.com/docker-for-windows/release-notes/)

I would like to be able to index an external drive called F:\

Kind regards,

Kurt

**Pull request merged**
