### PR TITLE
Add database server documentation

### PR DESCRIPTION
**Pull request by aaron-trout**

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Isn't database setup automatic? I don't remember performing these steps when installing PhotoPrism.

**Comment by aaron-trout** [comment]
By default you'll get the SQLite database, but these instructions are for setting up a MySQL or MariaDB database instead. I ran into issues with default collation/charset on my DB server and managed to find these values from the Docker Compose example at https://dl.photoprism.org/docker/docker-compose.yml so just wanted to document those in case other people ran into similar issues.

**Comment by lastzero** [comment]
No extra steps needed if you use our example config. Should put the more advanced topics in a separate corner so that less experienced users don't get confused.

**Comment by lastzero** [comment]
We'll put this in our new advanced section :+1:

**Pull request merged**
